name: Build DLL

on: 
  push:
  workflow_dispatch:

jobs:
  build:
    runs-on: windows-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      
    - name: Setup Visual Studio
      uses: microsoft/setup-msbuild@v2
      
    - name: Compile DLL
      run: |
        cl.exe /LD /MT /EHsc /std:c++17 main.cpp /Fe:CS2_Cheat.dll /link gdi32.lib user32.lib
      shell: cmd
        
    - name: Upload DLL
      uses: actions/upload-artifact@v4
      with:
        name: CS2-Cheat-DLL
        path: CS2_Cheat.dll
